image: java:8-jdk

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - ./gradlew build
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  only:
    - /^[0-9]+.[0-9]+.[0-9]+.*$/
  script:
    - ./gradlew -PVersion=$CI_COMMIT_REF_NAME publish
